---
title: "Graphs"
output: html_document
---

```{r}
library(DiagrammeR)
```


```{r}

# Original models

a <- grViz("
digraph plate_notation {
  graph [layout = dot, rankdir = LR, ranksep = 1.2]

  // Nodes with uniform size
  node [shape = circle, style = filled, fillcolor = white, fixedsize = true, width = 1]

  A     [label = A]
  A1    [label = <<I>κ</I><SUP>A</SUP>>]
  A2    [label = <1-<I>κ</I><SUP>A</SUP>>]
  Succes[label = <<I>H</I>A>]
  G1    [label = 'ψA']
  G2    [label = 'ψB']
  G3    [label = 'ψC']
  G4    [label = 'ψD']
  F1    [label = <<I>H</I>A>] 
  F2    [label = <<I>M</I>A>]
  F3    [label = <<I>M</I>A>]
  F4    [label = <<I>M</I>A>]

  // Force Succes and F1–F4 to same rank
  { rank = same; Succes; F1; F2; F3; F4 }

  // Knowlegde vs. Guess Edges 
  A -> A1 
  A -> A2 
  
  // Knowlegde edges from A1
  A1 -> Succes

  // Guess edges from A2
  A2 -> G1 
  A2 -> G2 
  A2 -> G3 
  A2 -> G4 
  
  // Outcome from guess edges
  G1 -> F1
  G2 -> F2
  G3 -> F3
  G4 -> F4
}
")

b <- grViz("
digraph plate_notation {
  graph [layout = dot, rankdir = LR, ranksep = 1.2]

  // Nodes with uniform size
  node [shape = circle, style = filled, fillcolor = white, fixedsize = true, width = 1]

  B     [label = B]
  B1    [label = <<I>κ</I><SUP>B</SUP>>]
  B2    [label = <1-<I>κ</I><SUP>B</SUP>>]
  Succes[label = <<I>H</I>B>]
  G1    [label = 'ψA']
  G2    [label = 'ψB']
  G3    [label = 'ψC']
  G4    [label = 'ψD']
  F1    [label = <<I>F</I>A>] 
  F2    [label = <<I>H</I>B>]
  F3    [label = <<I>M</I>B>]
  F4    [label = <<I>M</I>B>]

  // Force Succes and F1–F4 to same rank
  { rank = same; Succes; F1; F2; F3; F4 }

  // Knowlegde vs. Guess Edges 
  B -> B1 
  B -> B2 
  
  // Knowlegde edges from A1
  B1 -> Succes

  // Guess edges from A2
  B2 -> G1 
  B2 -> G2 
  B2 -> G3 
  B2 -> G4 
  
  // Outcome from guess edges
  G1 -> F1
  G2 -> F2
  G3 -> F3
  G4 -> F4
}
")

c <- grViz("
digraph plate_notation {
  graph [layout = dot, rankdir = LR, ranksep = 1.2]

  // Nodes with uniform size
  node [shape = circle, style = filled, fillcolor = white, fixedsize = true, width = 1]

  C     [label = C]
  C1    [label = <<I>κ</I><SUP>C</SUP>>]
  C2    [label = <1-<I>κ</I><SUP>C</SUP>>]
  Succes[label = <<I>H</I>C>]
  G1    [label = 'ψA']
  G2    [label = 'ψB']
  G3    [label = 'ψC']
  G4    [label = 'ψD']
  F1    [label = <<I>F</I>A>] 
  F2    [label = <<I>F</I>B>]
  F3    [label = <<I>H</I>C>]
  F4    [label = <<I>M</I>C>]

  // Force Succes and F1–F4 to same rank
  { rank = same; Succes; F1; F2; F3; F4 }

  // Knowlegde vs. Guess Edges 
  C -> C1 
  C -> C2 
  
  // Knowlegde edges from A1
  C1 -> Succes

  // Guess edges from A2
  C2 -> G1 
  C2 -> G2 
  C2 -> G3 
  C2 -> G4 
  
  // Outcome from guess edges
  G1 -> F1
  G2 -> F2
  G3 -> F3
  G4 -> F4
}
")

d <- grViz("
digraph plate_notation {
  graph [layout = dot, rankdir = LR, ranksep = 1.2]

  // Nodes with uniform size
  node [shape = circle, style = filled, fillcolor = white, fixedsize = true, width = 1]

  D     [label = D]
  D1    [label = <<I>κ</I><SUP>D</SUP>>]
  D2    [label = <1-<I>κ</I><SUP>D</SUP>>]
  Succes[label = <<I>H</I>D>]
  G1    [label = 'ψA']
  G2    [label = 'ψB']
  G3    [label = 'ψC']
  G4    [label = 'ψD']
  F1    [label = <<I>F</I>A>] 
  F2    [label = <<I>F</I>B>]
  F3    [label = <<I>F</I>C>]
  F4    [label = <<I>H</I>D>]

  // Force Succes and F1–F4 to same rank
  { rank = same; Succes; F1; F2; F3; F4 }

  // Knowlegde vs. Guess Edges 
  D -> D1 
  D -> D2 
  
  // Knowlegde edges from A1
  D1 -> Succes

  // Guess edges from A2
  D2 -> G1 
  D2 -> G2 
  D2 -> G3 
  D2 -> G4 
  
  // Outcome from guess edges
  G1 -> F1
  G2 -> F2
  G3 -> F3
  G4 -> F4
}
")

a
b
c
d

```


```{r}
# new model
A <- grViz("
digraph plate_notation {
  graph [layout = dot, rankdir = LR, ranksep = 1.2]

  // Nodes with uniform size
  node [shape = circle, style = filled, fillcolor = white, fixedsize = true, width = 1]

  A     [label = A]
  A1    [label = <<I>κ</I><SUP>A</SUP>>]
  A2    [label = <1-<I>κ</I><SUP>A</SUP>>]
  Succes[label = <<I>H</I>A>]
  G1    [label = 'ψA']
  G2    [label = 'ψa']
  G3    [label = 'ψB']
  G4    [label = 'ψb']
  G5    [label = 'ψC']
  G6    [label = 'ψc']
  G7    [label = 'ψD']
  G8    [label = 'ψd']
  F1    [label = <<I>H</I>A>] 
  F2    [label = <<I>F</I>A>]
  F3    [label = <<I>F</I>B>]
  F4    [label = <<I>F</I>B>]
  F5    [label = <<I>F</I>C>] 
  F6    [label = <<I>F</I>C>]
  F7    [label = <<I>F</I>D>]
  F8    [label = <<I>F</I>D>]
  
  // Force Succes and F1–F4 to same rank
  { rank = same; Succes; F1; F2; F3; F4 }
  { rank = same; A1; A2 }

  // Knowlegde vs. Guess Edges 
  A -> A1 
  A -> A2 
  
  // Knowlegde edges from A1
  A1 -> Succes
  A1 -> Succes [style=invis]

  // Guess edges from A2
  A2 -> G1
  A2 -> G2
  A2 -> G3
  A2 -> G4
  A2 -> G5
  A2 -> G6
  A2 -> G7 
  A2 -> G8
  
  // Outcome from guess edges
  G1 -> F1
  G2 -> F2
  G3 -> F3
  G4 -> F4
  G5 -> F5
  G6 -> F6
  G7 -> F7
  G8 -> F8
}
")

B <- grViz("
digraph plate_notation {
  graph [layout = dot, rankdir = LR, ranksep = 1.2]

  // Nodes with uniform size
  node [shape = circle, style = filled, fillcolor = white, fixedsize = true, width = 1]

  A     [label = B]
  A1    [label = <<I>κ</I><SUP>B</SUP>>]
  A2    [label = <1-<I>κ</I><SUP>B</SUP>>]
  Succes[label = <<I>H</I>B>]
  G1    [label = 'ψa']
  G2    [label = 'ψB']
  G3    [label = 'ψb']
  G4    [label = 'ψC']
  G5    [label = 'ψc']
  G6    [label = 'ψD']
  G7    [label = 'ψd']
  F1    [label = <<I>F</I>A>] 
  F2    [label = <<I>H</I>B>]
  F3    [label = <<I>F</I>B>]
  F4    [label = <<I>F</I>C>]
  F5    [label = <<I>F</I>C>] 
  F6    [label = <<I>F</I>D>]
  F7    [label = <<I>F</I>D>]
  
  // Force Succes and F1–F4 to same rank
  { rank = same; Succes; F1; F2; F3; F4 }
  { rank = same; A1; A2 }

  // Knowlegde vs. Guess Edges 
  A -> A1 
  A -> A2 
  
  // Knowlegde edges from A1
  A1 -> Succes
  A1 -> Succes [style=invis]

  // Guess edges from A2
  A2 -> G1
  A2 -> G2
  A2 -> G3
  A2 -> G4
  A2 -> G5
  A2 -> G6
  A2 -> G7 
  
  // Outcome from guess edges
  G1 -> F1
  G2 -> F2
  G3 -> F3
  G4 -> F4
  G5 -> F5
  G6 -> F6
  G7 -> F7
}
")

C <- grViz("
digraph plate_notation {
  graph [layout = dot, rankdir = LR, ranksep = 1.2]

  // Nodes with uniform size
  node [shape = circle, style = filled, fillcolor = white, fixedsize = true, width = 1]

  A     [label = C]
  A1    [label = <<I>κ</I><SUP>C</SUP>>]
  A2    [label = <1-<I>κ</I><SUP>C</SUP>>]
  Succes[label = <<I>H</I>C>]
  G1    [label = 'ψa']
  G2    [label = 'ψb']
  G3    [label = 'ψC']
  G4    [label = 'ψc']
  G5    [label = 'ψD']
  G6    [label = 'ψd']
  F1    [label = <<I>F</I>A>] 
  F2    [label = <<I>F</I>B>]
  F3    [label = <<I>H</I>C>]
  F4    [label = <<I>F</I>C>]
  F5    [label = <<I>F</I>D>] 
  F6    [label = <<I>F</I>D>]
  
  // Force Succes and F1–F4 to same rank
  { rank = same; Succes; F1; F2; F3; F4 }
  { rank = same; A1; A2 }

  // Knowlegde vs. Guess Edges 
  A -> A1 
  A -> A2 
  
  // Knowlegde edges from A1
  A1 -> Succes
  A1 -> Succes [style=invis]

  // Guess edges from A2
  A2 -> G1
  A2 -> G2
  A2 -> G3
  A2 -> G4
  A2 -> G5
  A2 -> G6
  
  // Outcome from guess edges
  G1 -> F1
  G2 -> F2
  G3 -> F3
  G4 -> F4
  G5 -> F5
  G6 -> F6
}
")

D <- grViz("
digraph plate_notation {
  graph [layout = dot, rankdir = LR, ranksep = 1.2]

  // Nodes with uniform size
  node [shape = circle, style = filled, fillcolor = white, fixedsize = true, width = 1]

  A     [label = D]
  A1    [label = <<I>κ</I><SUP>D</SUP>>]
  A2    [label = <1-<I>κ</I><SUP>D</SUP>>]
  Succes[label = <<I>H</I>D>]
  G1    [label = 'ψa']
  G2    [label = 'ψb']
  G3    [label = 'ψc']
  G4    [label = 'ψD']
  G5    [label = 'ψd']
  F1    [label = <<I>F</I>A>] 
  F2    [label = <<I>F</I>B>]
  F3    [label = <<I>F</I>C>]
  F4    [label = <<I>H</I>D>]
  F5    [label = <<I>F</I>D>] 
  
  // Force Succes and F1–F4 to same rank
  { rank = same; Succes; F1; F2; F3; F4 }
  { rank = same; A1; A2 }

  // Knowlegde vs. Guess Edges 
  A -> A1 
  A -> A2 
  
  // Knowlegde edges from A1
  A1 -> Succes
  A1 -> Succes [style=invis]

  // Guess edges from A2
  A2 -> G1
  A2 -> G2
  A2 -> G3
  A2 -> G4
  A2 -> G5

  // Outcome from guess edges
  G1 -> F1
  G2 -> F2
  G3 -> F3
  G4 -> F4
  G5 -> F5
}
")

A
B
C
D


```


```{r}

A2 <- grViz("
digraph plate_notation {
  graph [layout = dot, rankdir = LR, ranksep = 1.2]

  // Nodes with uniform size
  node [shape = circle, style = filled, fillcolor = white, fixedsize = true, width = 1]

  A     [label = A]
  A1    [label = <<I>κ</I><SUP>A</SUP>>]
  A2    [label = <1-<I>κ</I><SUP>A</SUP>>]
  Succes[label = <<I>H</I>A>]
  G1    [label = 'ψA']
  G2    [label = 'ψa']
  G3    [label = 'ψB']
  G4    [label = 'ψb']
  G5    [label = 'ψC']
  G6    [label = 'ψc']
  G7    [label = 'ψD']
  G8    [label = 'ψd']
  F1    [label = <<I>H</I>A>] 
  F2    [label = <<I>F</I>A>]
  F3    [label = <<I>F</I>B>]
  F4    [label = <<I>F</I>C>] 
  F5    [label = <<I>F</I>D>]
  
  // Force Succes and F1–F4 to same rank
  { rank = same; Succes; F1; F2; F3; F4 }
  { rank = same; A1; A2 }

  // Knowlegde vs. Guess Edges 
  A -> A1 
  A -> A2 
  
  // Knowlegde edges from A1
  A1 -> Succes
  A1 -> Succes [style=invis]

  // Guess edges from A2
  A2 -> G1
  A2 -> G2
  A2 -> G3
  A2 -> G4
  A2 -> G5
  A2 -> G6
  A2 -> G7 
  A2 -> G8
  
  // Outcome from guess edges
  G1 -> F1
  G2 -> F2
  G3 -> F3
  G4 -> F3
  G5 -> F4
  G6 -> F4
  G7 -> F5
  G8 -> F5
}
")

B <- grViz("
digraph plate_notation {
  graph [layout = dot, rankdir = LR, ranksep = 1.2]

  // Nodes with uniform size
  node [shape = circle, style = filled, fillcolor = white, fixedsize = true, width = 1]

  A     [label = B]
  A1    [label = <<I>κ</I><SUP>B</SUP>>]
  A2    [label = <1-<I>κ</I><SUP>B</SUP>>]
  Succes[label = <<I>H</I>B>]
  G1    [label = 'ψa']
  G2    [label = 'ψB']
  G3    [label = 'ψb']
  G4    [label = 'ψC']
  G5    [label = 'ψc']
  G6    [label = 'ψD']
  G7    [label = 'ψd']
  F1    [label = <<I>F</I>A>] 
  F2    [label = <<I>H</I>B>]
  F3    [label = <<I>F</I>B>]
  F4    [label = <<I>F</I>C>]
  F5    [label = <<I>F</I>C>] 
  F6    [label = <<I>F</I>D>]
  F7    [label = <<I>F</I>D>]
  
  // Force Succes and F1–F4 to same rank
  { rank = same; Succes; F1; F2; F3; F4 }
  { rank = same; A1; A2 }

  // Knowlegde vs. Guess Edges 
  A -> A1 
  A -> A2 
  
  // Knowlegde edges from A1
  A1 -> Succes
  A1 -> Succes [style=invis]

  // Guess edges from A2
  A2 -> G1
  A2 -> G2
  A2 -> G3
  A2 -> G4
  A2 -> G5
  A2 -> G6
  A2 -> G7 
  
  // Outcome from guess edges
  G1 -> F1
  G2 -> F2
  G3 -> F3
  G4 -> F4
  G5 -> F5
  G6 -> F6
  G7 -> F7
}
")

C <- grViz("
digraph plate_notation {
  graph [layout = dot, rankdir = LR, ranksep = 1.2]

  // Nodes with uniform size
  node [shape = circle, style = filled, fillcolor = white, fixedsize = true, width = 1]

  A     [label = C]
  A1    [label = <<I>κ</I><SUP>C</SUP>>]
  A2    [label = <1-<I>κ</I><SUP>C</SUP>>]
  Succes[label = <<I>H</I>C>]
  G1    [label = 'ψa']
  G2    [label = 'ψb']
  G3    [label = 'ψC']
  G4    [label = 'ψc']
  G5    [label = 'ψD']
  G6    [label = 'ψd']
  F1    [label = <<I>F</I>A>] 
  F2    [label = <<I>F</I>B>]
  F3    [label = <<I>H</I>C>]
  F4    [label = <<I>F</I>C>]
  F5    [label = <<I>F</I>D>] 
  F6    [label = <<I>F</I>D>]
  
  // Force Succes and F1–F4 to same rank
  { rank = same; Succes; F1; F2; F3; F4 }
  { rank = same; A1; A2 }

  // Knowlegde vs. Guess Edges 
  A -> A1 
  A -> A2 
  
  // Knowlegde edges from A1
  A1 -> Succes
  A1 -> Succes [style=invis]

  // Guess edges from A2
  A2 -> G1
  A2 -> G2
  A2 -> G3
  A2 -> G4
  A2 -> G5
  A2 -> G6
  
  // Outcome from guess edges
  G1 -> F1
  G2 -> F2
  G3 -> F3
  G4 -> F4
  G5 -> F5
  G6 -> F6
}
")

D <- grViz("
digraph plate_notation {
  graph [layout = dot, rankdir = LR, ranksep = 1.2]

  // Nodes with uniform size
  node [shape = circle, style = filled, fillcolor = white, fixedsize = true, width = 1]

  A     [label = D]
  A1    [label = <<I>κ</I><SUP>D</SUP>>]
  A2    [label = <1-<I>κ</I><SUP>D</SUP>>]
  Succes[label = <<I>H</I>D>]
  G1    [label = 'ψa']
  G2    [label = 'ψb']
  G3    [label = 'ψc']
  G4    [label = 'ψD']
  G5    [label = 'ψd']
  F1    [label = <<I>F</I>A>] 
  F2    [label = <<I>F</I>B>]
  F3    [label = <<I>F</I>C>]
  F4    [label = <<I>H</I>D>]
  F5    [label = <<I>F</I>D>] 
  
  // Force Succes and F1–F4 to same rank
  { rank = same; Succes; F1; F2; F3; F4 }
  { rank = same; A1; A2 }

  // Knowlegde vs. Guess Edges 
  A -> A1 
  A -> A2 
  
  // Knowlegde edges from A1
  A1 -> Succes
  A1 -> Succes [style=invis]

  // Guess edges from A2
  A2 -> G1
  A2 -> G2
  A2 -> G3
  A2 -> G4
  A2 -> G5

  // Outcome from guess edges
  G1 -> F1
  G2 -> F2
  G3 -> F3
  G4 -> F4
  G5 -> F5
}
")

A2
#B2
#C2
#D2


```



